alias: Clothes Washer Active
description: ""
mode: single
triggers:
  - type: power
    device_id: 3774c62b5c9bf57654e222d9d8b2fff5
    entity_id: sensor.washer_plug_energy_power
    domain: sensor
    above: 4
    below: 999999999
    for:
      hours: 0
      minutes: 10
      seconds: 0
    trigger: device
conditions: []
actions:
  - data:
      value: Washing
    target:
      entity_id: input_text.clothes_washer_state
    action: input_text.set_value
