alias: Clothes Dryer Active
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.clothes_dryer_state
    for:
      hours: 0
      minutes: 10
      seconds: 0
    from:
      - "off"
    to:
      - "on"
conditions: []
actions:
  - data:
      value: Drying
    target:
      entity_id: input_text.clothes_dryer_state
    action: input_text.set_value
  - action: input_boolean.turn_off
    target:
      entity_id: input_boolean.washer_finished_dryer_not_yet_run
    data: {}
mode: single
